kind: pipeline
type: docker
name: default
  # Note: Use as long as the reason for this suddenly occurring error
  #       remains unknown. Also use it if the error suddenly happens during
  #       productive use after problem free operations
clone:
  skip_verify: true


steps:

- name: execute - execute main.sh
  image: ubuntu:22.04
  commands:
  - cd ./${DRONE_BRANCH}
  - chmod +x main.sh
  - bash ./main.sh < input.txt > output.txt

- name: decrypt - managing secret solution files
#  # cp. https://hub.docker.com/r/frapsoft/openssl
  image: frapsoft/openssl
  environment:
    KEY:
      from_secret: key
  commands:
    - openssl enc -d -aes-256-cbc -md sha256 -pass env:KEY -in ./${DRONE_BRANCH}/solution.sh.enc -out ./${DRONE_BRANCH}/solution.sh


- name: check - check if main.sh is correct
  image: ubuntu:22.04
  commands:
  - cd ./${DRONE_BRANCH}
  - chmod +x ./solution.sh
  - bash ./solution.sh > expected_result.txt
  - diff -s -q output.txt expected_result.txt

trigger:
  branch:
  - feature*