kind: pipeline
type: docker
name: default
  # Note: Use as long as the reason for this suddenly occurring error
  #       remains unknown. Also use it if the error suddenly happens during
  #       productive use after problem free operations
clone:
  skip_verify: true


steps:

- name: check - final test step
  image: ubuntu:18.04
  commands:
  - echo ${DRONE_GIT_HTTP_URL}
  - echo ${DRONE_BRANCH}
  - pwd
  - echo "--- Drone pipeline test successfully terminated ---"

trigger:
  branch:
  - master
  - feature*