kind: pipeline
type: docker
name: default
  # Note: Use as long as the reason for this suddenly occurring error
  #       remains unknown. Also use it if the error suddenly happens during
  #       productive use after problem free operations
clone:
  skip_verify: true


steps:

- name: process main
  image: python:3.10.4
  commands:
  - cd ${DRONE_BRANCH}
  - python main.py > output.txt

- name: decrypt - managing secret solution files
  # cp. https://hub.docker.com/r/frapsoft/openssl
  image: frapsoft/openssl
  environment:
    KEY:
      from_secret: key
  commands:
  - openssl enc -d -aes-256-cbc -md sha256 -pass env:KEY -in ./${DRONE_BRANCH}/solution.py.enc -out ./${DRONE_BRANCH}/solution.py


- name: check if main is correct
  image: python:3.10.4
  commands:
  - cd ${DRONE_BRANCH}
  - python solution.py > expected_result.txt
  - diff -s -q output.txt expected_result.txt

trigger:
  branch:
  - feature*