# Pull the base image
FROM ubuntu:22.04


# Nginx and OpenSSH Installation
RUN apt-get -y update && apt-get -y install nginx 
RUN apt-get -y install openssh-server


#RUN service ssh start
WORKDIR /root/.ssh
RUN chmod 700 /root/.ssh 


#key-based root login via ssh
RUN echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC02n64SkmBNQILhm71tohUIL3cZV3ReIODE32dyY167nilTWKctGbp9wpXSVL+ZdK1PJGR5MCcYlU52CQrBPx2m2QJm2yIkkgMukzRyJB+Xor3t4pMDKf91rQiFp9Tp5gujawiacqDM1+Bk/mvZSNgdJ+UGVGq6qMFh0EfM0xIMRp3P7JFPQKeW826zRrdTmew/vfrL5jIh+8apsLm4KzmS1aKhu3dM7UUsS700QfebZksg40Ncy97sYScKttZpGxSGZ5/athLs6zcCSrziVd+RTK0WXPBhw2iZ1bjsbrXeleSY2udhWPm7aSFSXE41pmxj975tgxrtqTJMmC7/Xcx" > /root/.ssh/authorized_keys


#admin root privileges
RUN echo 'admin ALL=(ALL) NOPASSWD: ALL'|tee -a /etc/sudoers
#Denying password-based login via ssh
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config